import { Palette, Font } from "styling/style.slint";
import { ComboBox, TextEdit, VerticalBox, Button } from "std-widgets.slint";
import { Project } from "pages/projects/projects.slint";

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 500px;

    min-width: 720px;
    min-height: 450px;

    title: "STM32 Studio";

    background: Palette.background;

    default-font-family: Font.font-ui;
    default-font-size: 13px;
    default-font-weight: 400;

    callback new-project();
    callback open-project();
    callback open-recent-project(string);

    VerticalLayout {
        HorizontalLayout {
            alignment: center;
            cross-axis-alignment: center;

            padding: 20px;

            Project {
                max-width: 750px;
                horizontal-stretch: 0;

                border-color: Palette.border;
                border-width: 1px;
                border-radius: 4px;

                new-project => { new-project(); }
                open-project => { open-project(); }
                open-recent-project(path) => { open-recent-project(path); }
            }
        }
    }
}
