import { ComboBox } from "std-widgets.slint";
import { AppPalette } from "../styling/style.slint";
export component LabeledComboBox inherits VerticalLayout {
    in property <string> label;
    in property <string> description;
    in property <[string]> model;
    in-out property <int> current-index: 0;

    spacing: 8px;
    cross-axis-alignment: stretch;

    Text {
        text: root.label;
        vertical-alignment: center;
        horizontal-alignment: left;

        font-weight: 400;
        font-size: 13px;
        color: AppPalette.text-secondary;
    }

    ComboBox {
        model: root.model;
        current-index <=> root.current-index;
    }

    if root.description != "":
        Text {
            text: root.description;
            font-size: 12px;
            color: AppPalette.text-secondary;
            wrap: word-wrap;
        }
}
