[package]
name = "backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
firmware-targets.workspace = true
generation = { workspace = true, features = ["serde"] }
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
uuid = { version = "1.26.1", features = ["serde", "v4"] }
