[package]
name = "studio-dioxus"
version = "0.1.0"
authors = ["SinaMajdieh <sina.majdieh@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend.workspace = true
dioxus = { version = "0.7.1", features = ["router"] }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
firmware-targets.workspace = true
rfd.workspace = true
strum.workspace = true

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
web = ["dioxus/web"]
