export global Palette {
    out property<color> background: #101216;
    out property<color> surface: #171A20;
    out property<color> surface-2: #181c21;
    out property<color> surface-3: #1e2329;
    out property <color> surface-hover: #1D2128;
    out property<color> border: #292E37;
    out property<color> border-strong: #343b45;

    out property<color> text-primary: #E8EAED;
    out property<color> text-secondary: #969DA8;
    out property<color> text-muted: #626A76;

    out property<color> accent: #4C9AFF;
    out property<color> accent-hover: #9cabff;
    out property<color> accent-soft: #242b48;

    out property<color> success: #56d69a;
    out property<color> warning: #e5ba65;
    out property<color> error: #ef6f78;
}
