[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
backend.workspace = true
clap = { version = "4", features = ["derive"] }
firmware-targets = { workspace = true, features = ["clap"] }
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml.workspace = true
