import { Theme } from "../theme.slint";
import { ScrollView } from "std-widgets.slint";

export component OutputPanel inherits Rectangle {
    in property<bool> open: false;
    in property<string> output: "Generating project...\nProject generated.\n\nBuilding...\narm-none-eabi-gcc main.c\nLinking firmware.elf\n\nBuild successful.\n\nOpenOCD\nProgramming target...\nVerified.\nResetting target.\n\nDone.";

    visible: root.open;
    height: root.open ? 184px : 0px;
    background: Theme.surface;
    border-width: 1px;
    border-color: Theme.border;

    Text {
        x: 18px;
        y: 14px;
        text: "OUTPUT";
        color: Theme.text-muted;
        font-family: Theme.font-ui;
        font-size: 9px;
        font-weight: 700;
    }

    ScrollView {
        x: 18px;
        y: 38px;
        width: parent.width - 36px;
        height: parent.height - 50px;
        vertical-scrollbar-policy: as-needed;
        horizontal-scrollbar-policy: always-off;

        Text {
            width: parent.width;
            text: root.output;
            color: Theme.text-secondary;
            font-family: Theme.font-mono;
            font-size: 10px;
            wrap: word-wrap;
        }
    }
}
