import { Font } from "styling/style.slint";
import { Palette } from "std-widgets.slint";
import { ScreenHost } from "screen-host.slint";
import { ProjectAction } from "screens/projects/project-action.slint";

export { Navigation } from "navigation.slint";
export { Screen } from "screen.slint";
export { ProjectAction } from "screens/projects/project-action.slint";

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 500px;

    title: "STM32 Studio";

    background: Palette.background;

    default-font-family: Font.font-ui;
    default-font-size: 13px;
    default-font-weight: 400;

    MenuBar {
        Menu {
            title: "File";

            MenuItem {
                title: "Projects";
                shortcut: @keys(Control + P);
                activated => { ProjectAction.open(); }
            }

            MenuSeparator {}
        }
    }

    ScreenHost {}
}
