import { Navigation } from "navigation.slint";
import { Screen } from "screen.slint";

import { Generation } from "screens/generation.slint";
import { NewProjectDialog } from "screens/projects/new-project.slint";
import { Project } from "screens/projects/projects.slint";

export component ScreenHost inherits Rectangle {
    background: transparent;

    VerticalLayout {
        if Navigation.current-screen == Screen.Project : Project {
            horizontal-stretch: 0;
        }

        if Navigation.current-screen == Screen.NewProject : NewProjectDialog {
            cancel => {
                Navigation.go-to(Screen.Project);
            }
        }

        if Navigation.current-screen == Screen.Generation : Generation {}
    }
}
