import { Navigation } from "navigation.slint";
import { Project } from "screens/projects/projects.slint";
import { Screen } from "screen.slint";
import { Palette } from "styling/style.slint";
import { Generation } from "screens/generation.slint";

export component ScreenHost  inherits Rectangle {
    background: transparent;
    if Navigation.current-screen == Screen.Project : VerticalLayout {
        HorizontalLayout {
            alignment: center;
            cross-axis-alignment: center;

            padding: 20px;

            Project {
                max-width: 750px;
                horizontal-stretch: 0;

                border-color: Palette.border;
                border-width: 1px;
                border-radius: 4px;
            }
        }
    }
    if Navigation.current-screen == Screen.Generation : Generation {}
}
