[package]
name = "studio-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
backend.workspace = true
firmware-targets.workspace = true
rfd.workspace = true
serde.workspace = true
slint = "1.17.1"
strum.workspace = true
thiserror.workspace = true
toml.workspace = true

[build-dependencies]
slint-build = "1.17.1"
