[package]
name = "studio-gpui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
backend.workspace = true
firmware-targets.workspace = true
gpui-kit = "0.6.6"
gpui-navigation = {
  git = "https://github.com/SinaMajdieh/gpui-navigation.git",
}
rfd.workspace = true
strum.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
