//! Generation output and statistics.
//!
//! Provider-specific responses are normalized into [`GenerationOutput`] and
//! accompanied by timing and token-usage information when available.

use std::time::Duration;

/// Result of a successful generation request.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GenerationOutput {
    /// Generated source code.
    pub code: String,

    /// Statistics collected while generating the response.
    pub statistics: GenerationStatistics,
}

/// Statistics collected during generation.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GenerationStatistics {
    /// Number of prompt tokens, when reported by the provider.
    pub prompt_tokens: Option<u64>,

    /// Number of tokens generated by the model.
    pub generated_tokens: u64,

    /// Total duration of the generation request.
    pub elapsed: Duration,
}

impl GenerationStatistics {
    /// Returns the observed generation throughput in tokens per second.
    ///
    /// Returns `0.0` when the recorded duration is zero.
    pub fn tokens_per_second(&self) -> f64 {
        let seconds = self.elapsed.as_secs_f64();

        if seconds == 0.0 {
            return 0.0;
        }

        self.generated_tokens as f64 / seconds
    }
}
