[package]
name = "generation"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = { version = "0.41.3", features = ["chat-completion"] }
ollama-client = { path = "../ollama-client", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.20"
tokio = "1.53.1"
toml = "0.9"
