[package]
name = "generation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-openai = { version = "0.41.3", features = ["chat-completion"] }
ollama-client.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
